# name=("sandro")
# age=15
# hight=1.79
# status="student"
# print(type(name))
# print(type(age))
# print(type(hight))
# print(type(status))
# city="tbilisi"
# country="georgia"
# print("i live in "+ city +" "+country)
# age=int(input())
# print(age+14)
# a=float(input())
# b=float(input())
# c=int(a*b)
# print(c)
# A=int(input())
# B=int(input())
# print(A/B)
# print(A//B)
# text="GOA"
# print(text*5)
# NAME="bondo"
# AGE=str(5)
# love="py"
# print("hello "+ NAME +"you are "+ AGE +" years old and youre loved program is "+ love )
# celsius=20
# farenhite=(celsius*9/5)+32
# print(farenhite)


# A="20"
# B=5
# print(B+int(A))
# print(A+str(B))
# age=int(input())
# print(age+5)
# num1=15
# num2=num1/2
# num3=num1//2
# print(num2)
# print(num3)
#ert xaziani gayofa yoveltvis gamoitans floats xolo 2 xaziani gayofa gamoitans mtel gayofis nishans nashtis gareshe
# age=int(input())
# print(age>=18)
# for i in range(10):
#     i=i+1
#     print(i*i)
# secret_number=7
# guess=int(input())
# while guess !=secret_number:
#     guess=int(input())
# print("access granted!")
# num1=int(input())
# jami=0
# num2=int(input())
# while num1 <= num2:
#     jami=jami+num1
#     num1=num1+1
#     print(jami)
for i in range(100,2):
    print(i)