# password="sandro123"
# a=input()
# while a != password:
#     a=input()
# print("access granted!")
# i=1
# jami=0
# while i<=20:
#     jami=jami+i
#     i=i+1
#     print(jami)
# 
# num1=int(input())
# jami=0
# num2=int(input())
# while num1<=num2:
#     jami=jami+num1
#     num1=num1+1
#     print(jami)
secret_num=7
num1=int(input())
while num1 !=secret_num:
    num1=int(input())
print("access")