# name=input()
# if name=="sandro":
#     print("Hello admin!")
# elif name=="berdia":
#     print("Hello moderator!")
# else:
#     print("Hello user!")

# a=int(input())
# b=int(input())
# if a>b:
#     print("first number is greater then second")
# elif a<b:
#     print("second number is greater then first")
# else:
#     print("both numbers are equal")

age=18
if age<18:
    print("underage")
elif age==18:
    print("teen")
else:
    print("adult")