# colors=["blue","red","purple"]
# print(colors)
# animals=["cat","dog","tiger"]
# print(animals[0])
# for i in range(5):
#     print(i)
# for i in range(3):
#     print("hello")
# a=0
# while a<4:
#     print(a)
#     a=a+1
for i in range(11):
    print(i)
for i in range(2,12,2):
    print(i)
for i in range(5):
    print("Python is fun")
b=2
while b<12:
    print(b)
    b=b+2
number = 1
while number<10:
    print(number)
    number=number+2
for number in range(1,6):
    print("number",number)
total=0
for i in range(1,6):
    total+=i
    print(total)
for number in range(1,11):
    if number>5:
        continue
    print(number)